ClassroomFund.FundUI/Controllers/BuildingsController.cs
using ClassroomFund.Models;
using ClassroomFund.Services.Classrooms.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers
{
    public class BuildingsController : Controller
    {
        private readonly IBuildingService _buildingService;

        public BuildingsController(IBuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        // GET: BuildingsController
        public async Task<ActionResult> Index()
        {
            var model = new MainModel();
            model.Buildings = await _buildingService.GetAllBuildingsWithInfo();
            model.BuildingNumber = model.Buildings?.Count ?? 0;
            model.RoomsNumber = 42;
            model.TotalArea = 4294.2345678;


            return View(model);
        }

        public async Task<ActionResult> BuildingOverview(Guid id)
        {
            Building building = await _buildingService.GetByIdWithInfo(id);
            return PartialView(building);
        }
    }

    public class MainModel
    {
        public List<Building>? Buildings { get; set; }

        public int BuildingNumber { get; set; }

        public int RoomsNumber { get; set; }

        public double TotalArea { get; set; }
    }
}

ClassroomFund.FundUI/Controllers/FloorsController.cs
using System.ComponentModel.DataAnnotations;
using ClassroomFund.Models;
using ClassroomFund.Services.Classrooms.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers;

public class FloorsController : Controller
{
    private readonly IFloorInfoService _floorInfo;
    private readonly IRoomService _roomService;
    private readonly IBuildingService _buildingService;

    public FloorsController(IFloorInfoService floorInfo, IRoomService roomService, IBuildingService buildingService)
    {
        _floorInfo = floorInfo;
        _roomService = roomService;
        _buildingService = buildingService;
    }

    public async Task<IActionResult> Overview([Required] Guid id)
    {
        var floor = await _floorInfo.GetByIdWithInfo(id);
        OverviewViewModel model = new OverviewViewModel();
        model.FloorInfo = floor;
        if (floor != null)
        {
            model.Rooms = await _roomService.GetRoomsByFloorId(id);
            return View(model);
        }

        return NotFound();
    }

    public async Task<IActionResult> AddFloorFirstStep(Guid buildingId)
    {
        var building = await _buildingService.GetBuildingById(buildingId);
        if (building == null)
        {
            return NotFound();
        }

        var model = new AddFloorFirstStepViewModel();
        model.Building = building;
        model.LatestFloorNumber = await _buildingService.GetLastFloorNumber(buildingId) + 1;
        model.FloorInfo = new()
        {
            FloorNumber = model.LatestFloorNumber,
            Building = buildingId,
            ClassroomToImageMapping = "[]",
            Id = Guid.NewGuid()
        };
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddFloorPost([FromForm] AddFloorFirstStepViewModel model)
    {
        await _floorInfo.AddFloor(model.FloorInfo);
        return Redirect(model.RedirectToUrl);
    }
}

public class OverviewViewModel
{
    public FloorInfo FloorInfo { get; set; }

    public List<Room>? Rooms { get; set; }
}

public class AddFloorFirstStepViewModel
{
    public Building? Building { get; set; }

    public int LatestFloorNumber { get; set; }

    public FloorInfo? FloorInfo { get; set; }

    public string RedirectToUrl { get; set; }
}

ClassroomFund.FundUI/Views/Buildings/BuildingOverview.cshtml
@using System.Globalization
@using ClassroomFund.ScheduleUI.Infrastructure
@using ClassroomFund.ScheduleUI.Models.Users
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ClassroomFund.Models.Building
@inject UserManager<ApplicationUser> userManager;
@inject SignInManager<ApplicationUser> signInManager;
@{
    var signedIn = signInManager.IsSignedIn(Context.User);
    var user = signedIn ? await userManager.GetUserAsync(Context.User) : null;
}

<script id="external_script" type="text/javascript"></script>
<script id="leaflet_script"></script>
<script>
    document.getElementById('leaflet_script').src = '/js/leaflet.js';
    document.getElementById('external_script').src = '/js/map_init.js';
    document.getElementById('external_script').onload = () => searchAndFill('@Model.Address.ToString(new CultureInfo("ru_RU"))');
</script>

<div class="row w-100">
    <div class="col">
        <h3>
            Информация о: "@Model.Name"
        </h3>
        <div class="card">
            <div class="list-group list-group-flush">
                <div class="list-group-item">
                    <span class="fw-bold text-dark">Адрес:</span> @Model.Address
                </div>
            </div>
            <div class="card-header">
                <h4>Этажи</h4>
            </div>
            <div class="list-group list-group-flush">
                @foreach (var floorInfo in Model.FloorInfoes.OrderBy(e => e?.FloorNumber).ToList())
                {
                    <div class="list-group-item d-inline-flex justify-content-center">
                        <div class="flex-grow-1">
                            <span class="fw-bold text-dark">Этаж</span> @floorInfo.FloorNumber
                        </div>
                        <div class="flex-grow-1">
                            <a class="btn btn-sm btn-primary  w-75" asp-controller="Floors" asp-action="Overview" asp-route-id="@floorInfo.Id">Просмотр</a>
                        </div>
                        @if (signedIn && await userManager.IsInRoleAsync(user, RolesConstants.AdminRole))
                        {
                            <div class="btn-group btn-group-sm" role="group">
                                <button class="btn btn-sm btn-light">Ред.</button>
                                <button class="btn btn-sm btn-warning">Удалить</button>
                            </div>
                        }
                    </div>
                }
                @if (signedIn && await userManager.IsInRoleAsync(user, RolesConstants.AdminRole))
                {
                    <div class="list-group-item d-inline-flex justify-content-center">
                        <a class="btn btn-primary" asp-controller="Floors" asp-action="AddFloorFirstStep" asp-route-buildingId="@Model.Id">Добавить новый этаж</a>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-4">
        <h4>Расположение корпуса</h4>
        <div id="map" style="height: 200px;"></div>
    </div>
</div>

ClassroomFund.FundUI/Views/Buildings/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using ClassroomFund.ScheduleUI.Models.Users
@using ClassroomFund.Services
@model ClassroomFund.ScheduleUI.Controllers.MainModel
@inject UserManager<ApplicationUser> userManager;
@inject SignInManager<ApplicationUser> signInManager;
@inject OverviewService overviewService;

@{
    var itemTemplate = "<div hx-get=\"/Buildings/BuildingOverview/${Id}\" hx-target=\"#buildingsView\" hx-swap=\"innerHTML\" hx-trigger=\"click\">${Name}</div>";
    var isLoggedIn = signInManager.IsSignedIn(Context.User);
    var overview = await overviewService.GetOverview();
}

<div class="row my-1">
    <div class="col-2">
        @if (isLoggedIn)
        {
            <h3>Поиск</h3>
            <hr/>
            <div class="my-1">
                <ejs-autocomplete id="games" dataSource="@ViewBag.data" placeholder="Кафедра или номер аудитории" class="border border-light border-1">
                    <e-data-manager adaptor="WebApiAdaptor" url="https://ej2services.syncfusion.com/production/web-services/api/Employees" crossDomain="true"></e-data-manager>
                    <e-autocomplete-fields value="FirstName"></e-autocomplete-fields>
                </ejs-autocomplete>
            </div>
        }

        <h3>Корпуса</h3>
        <hr/>
        <ejs-listview enable="true" id="listview" dataSource="Model.Buildings" template="@itemTemplate">
            <e-listview-fieldsettings text="Name">
            </e-listview-fieldsettings>
        </ejs-listview>
        <div class="e-card my-1 my-md-2 shadow border-1">
            <div class="e-card-content">
                Для продолжения выберите либо номер корпуса, либо воспользуйтесь поиском конкретной аудитории.
            </div>
        </div>
    </div>
    <div class="col" id="buildingsView">
        <div class="card">
            <div class="card-header">
                <h2>
                    Сводка по университету
                </h2>
            </div>
            <div class="card-body">
                <h5>
                    В распоряжении университета:
                </h5>
                <hr/>
                <p>
                    Корпусов: @overview.BuildingsNumber
                </p>
                <hr/>
                <p>
                    Аудиторий: @overview.RoomsCount
                </p>
                <hr/>
                <p>
                    Общая площадь помещений: @Html.Raw(overview.TotalArea.ToString("F2"))
                </p>
            </div>
        </div>
    </div>
</div>