ClassroomFund.FundUI/Controllers/BuildingsController.cs
using ClassroomFund.Models;
using ClassroomFund.Services.Classrooms.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers
{
    public class BuildingsController : Controller
    {
        private readonly IBuildingService _buildingService;

        public BuildingsController(IBuildingService buildingService)
        {
            _buildingService = buildingService;
        }

        // GET: BuildingsController
        public async Task<ActionResult> Index()
        {
            var model = new MainModel();
            model.Buildings = await _buildingService.GetAllBuildingsWithInfo();
            model.BuildingNumber = model.Buildings?.Count ?? 0;
            model.RoomsNumber = 42;
            model.TotalArea = 4294.2345678;


            return View(model);
        }

        public async Task<ActionResult> BuildingOverview(Guid id)
        {
            Building building = await _buildingService.GetByIdWithInfo(id);
            return PartialView(building);
        }
    }

    public class MainModel
    {
        public List<Building>? Buildings { get; set; }

        public int BuildingNumber { get; set; }

        public int RoomsNumber { get; set; }

        public double TotalArea { get; set; }
    }
}

ClassroomFund.FundUI/Controllers/ConstantsController.cs
using ClassroomFund.ScheduleUI.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers;

[Authorize(Roles = RolesConstants.AdminRole)]
public class ConstantsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

ClassroomFund.FundUI/Controllers/RequestsController.cs
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers;

public class RequestsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

ClassroomFund.FundUI/Controllers/RoomController.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using ClassroomFund.Models;
using ClassroomFund.Services.Classrooms.Interfaces;
using ClassroomFund.Services.Departments;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ClassroomFund.ScheduleUI.Controllers;

public class RoomController : Controller
{
    private readonly IRoomService _roomsService;
    private readonly IBuildingService _buildingService;
    private readonly IDepartmentsService _departmentsService;
    private readonly IFloorInfoService _floorInfoService;

    public RoomController(IRoomService roomsService, IBuildingService buildingService, IDepartmentsService departmentsService, IFloorInfoService floorInfoService)
    {
        _floorInfoService = floorInfoService;
        _departmentsService = departmentsService;
        _buildingService = buildingService;
        _roomsService = roomsService;
    }

    public async Task<IActionResult> Index()
    {
        RoomIndexViewModel model = new();
        var rooms = model.Rooms = await _roomsService.GetAll();
        var buildings = await _buildingService.GetAllBuildings();
        var departments = await _departmentsService.GetAll();
        model.RoomsTree = new List<object>();
        model.RoomsTree.AddRange(buildings.Select(e => new
        {
            e.Id,
            e.Name,
            HasChild = true,
            IsRoot = true
        }));
        model.RoomsTree.AddRange(rooms.Select((e) => new
        {
            e.Id,
            e.BuildingId,
            Name = e.RoomNumber,
            IsRoot = false
        }).OrderBy(e => e.Name));
        model.DepartmentsTree = new List<object>();
        model.DepartmentsTree.AddRange(departments.Select(e => new
        {
            e.Id,
            Name = e.DepartmentName,
            IsRoot = true,
            HasChild = true
        }));
        model.DepartmentsTree.AddRange(rooms.Select((e) => new
        {
            e.Id,
            DepartmentId = e.DepartmentId,
            Name = e.RoomNumber,
            IsRoot = false,
            HasChild = false
        }).OrderBy(e => e.Name));
        return View(model);
    }

    public async Task<IActionResult> Overview([Required]Guid id)
    {
        var info = await _roomsService.GetByIdWithInfo(id);
        RoomOverviewViewModel model = new();
        model.RoomInfo = info;
        return View(model);
    }

    public async Task<IActionResult> OverviewEmbed([Required]Guid id)
    {
        var info = await _roomsService.GetByIdWithInfo(id);
        RoomOverviewViewModel model = new();
        model.RoomInfo = info;
        return PartialView("Overview", model);
    }

    public async Task<IActionResult> Edit(Guid id)
    {
        var info = await _roomsService.GetByIdWithInfo(id);
        if (info == null)
        {
            return NotFound();
        }
        return View();
    }

    public async Task<IActionResult> AddRoomFirstStep(Guid floorId)
    {
        ViewBag.FloorId = floorId;
        var floor = await _floorInfoService.GetById(floorId);
        if (floor == null)
        {
            return NotFound();
        }
        return View(floor);
    }

    [HttpPost]
    public async Task<IActionResult> AddRoomSecondStep([FromForm] Guid floorId, [FromForm] string roomMap)
    {
        if (String.IsNullOrWhiteSpace(roomMap))
        {
            roomMap = "[]";
        }
        Point[] points = JsonSerializer.Deserialize<Point[]>(roomMap);

        AddRoomSecondStepModel model = new AddRoomSecondStepModel();
        model.FloorId = floorId;
        model.RoomMap = points;
        model.RoomTypes = (await _roomsService.GetRoomTypes())
            .Select(e => new SelectListItem(e.Name, e.Id.ToString()))
            .ToArray();
        model.RoomTargets = (await _roomsService.GetRoomTargets())
            .Select(e => new SelectListItem(e.TargetName, e.Id.ToString()))
            .ToArray();
        model.Departments = (await _departmentsService.GetAll())
            .Select(e => new SelectListItem(e.DepartmentName, e.Id.ToString()))
            .ToArray();
        model.FloorInfo = await _floorInfoService.GetByIdWithInfo(floorId);
        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddRoomComplete(AddRoomSecondStepModel model, [FromForm] string roomMap)
    {
        //model.NewRoom.FloorId = model.FloorId;
        var room = await _roomsService.AddRoom(model.NewRoom);
        var properties = await _roomsService.AddRoomInformation(model.NewRoomProperties);
        //TODO: add mapping insert
        await _floorInfoService.AddImageMapping(model.NewRoom.FloorId, model.NewRoom.Id, JsonSerializer.Deserialize<Point[]>( roomMap));
        if (model.SaveAndGoBack)
        {
            return RedirectToAction("Overview", "Floors" , model.FloorId);
        }
        else
        {
            return RedirectToAction("Overview", room?.Id);
        }
    }
}

public class RoomOverviewViewModel
{
    public Room RoomInfo { get; set; }
}

public class RoomIndexViewModel
{
    public List<Room> Rooms { get; set; }

    public List<Building> Buildings { get; set; }

    public List<Department> Departments { get; set; }

    public List<object> RoomsTree { get; set; }

    public List<object> DepartmentsTree { get; set; }
}

public class RoomEditViewModel
{
    public Room Target { get; set; }

    public List<RoomTarget> RoomTargets { get; set; }

    public List<RoomType> RoomTypes { get; set; }

    public FloorInfo Floor { get; set; }
}

public class AddRoomSecondStepModel
{
    public Guid FloorId { get; set; }
    
    public Point[] RoomMap { get; set; }

    public Guid NewRoomId { get; set; } = Guid.NewGuid();

    public Room NewRoom { get; set; }
    
    public FloorInfo FloorInfo { get; set; }
    
    public InternalRoomProperty NewRoomProperties { get; set; }

    public SelectListItem[] RoomTypes { get; set; }
    
    public SelectListItem[] RoomTargets { get; set; }
    
    public SelectListItem[] Departments { get; set; }
    
    public bool SaveAndGoBack { get; set; }
}

ClassroomFund.FundUI/Views/Shared/_Layout.cshtml
@using ClassroomFund.ScheduleUI.Infrastructure
@using ClassroomFund.ScheduleUI.Models.Users
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using Syncfusion.EJ2
@inject UserManager<ApplicationUser> userManager;
@inject SignInManager<ApplicationUser> signInManager;
@{
    var user = await userManager.GetUserAsync(Context.User);
    var roles = user != null ? await userManager.GetRolesAsync(user) : new List<string>();
}
<!DOCTYPE html>
<html lang="ru" class="h-100">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] Аудиторный фонд ГГТУ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/bootstrap5.css" asp-append-version="true"/>
    <script src="~/js/ej2.min.js"></script>
    <link rel="stylesheet" href="~/css/leaflet.css" asp-append-version="true"/>
</head>
<body class="d-flex flex-column h-100 my-0">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom shadow mb-2">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Аудиторный фонд</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (signInManager.IsSignedIn(Context.User))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Buildings" asp-action="Index">Корпуса</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Room" asp-action="Index">Аудитории</a>
                        </li>
                        @*<li class="nav-item dropdown">
                            <a class="nav-link" asp-area="" asp-controller="Requests" asp-action="Index">Заявки</a>
                        </li>*@
                        @if (await userManager.IsInRoleAsync(user, RolesConstants.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="userManagmentDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Пользователи
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="userManagmentDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Employees" asp-action="Index">Профили</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="UserManagement" asp-action="Index">Управление пользователями</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (await userManager.IsInRoleAsync(user, RolesConstants.SecretaryRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="equipmentDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Оборудование
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="equipmentDropdown">
                                    @if (await userManager.IsInRoleAsync(user, RolesConstants.AdminRole))
                                    {
                                        <li>
                                            <a class="dropdown-item" asp-controller="EquipmentProperty" asp-action="Index">Справочник свойств</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="EquipmentType" asp-action="Index">Категории оборудования</a>
                                        </li>
                                    }
                                    <li>
                                        <a class="dropdown-item" asp-controller="Equipment" asp-action="Index">Обзор</a>
                                    </li>
                                </ul>
                            </li>
                        }
                        @if (roles.Contains(RolesConstants.AdminRole) || roles.Contains(RolesConstants.RectorRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Departments" asp-action="Index">Кафедры</a>
                            </li>
                        }
                        @if (roles.Contains(RolesConstants.SecretaryRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Departments" asp-action="MyDepartmentOverview">Моя кафедра</a>
                            </li>
                        }
                        @if (User.IsInRole(RolesConstants.AdminRole))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Constants" asp-action="Index">Константы</a>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="navbar d-sm-inline-flex justify-content-between">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer mt-auto py-3 bg-dark">
    <div class="container text-muted">
        &copy; 2022 - Казутин Павел, <a href="mailto:me@ktsin.xyz">me@ktsin.xyz</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/htmx.min.js" defer></script>
<ejs-scripts></ejs-scripts>
<script src="~/js/localize.js"></script>
<script defer="defer">
</script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>