ClassroomFund.FundUI/Controllers/API/ConstantsApiController.cs
using System.Text.Json;
using ClassroomFund.Models;
using ClassroomFund.Services.Classrooms.Interfaces;
using ClassroomFund.Services.UserManagment.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers.API;

[Route("/api/Constants")]
public class ConstantsApiController : Controller
{
    private readonly IEmployeeService _employeeService;
    private readonly IRoomService _roomService;

    private readonly JsonSerializerOptions serializerOptions = new()
    {
        PropertyNamingPolicy = null
    };
    
    public ConstantsApiController(IEmployeeService employeeService, IRoomService roomService)
    {
        _roomService = roomService;
        _employeeService = employeeService;
    }

    #region EmployeeTitle

    [HttpGet("EmployeeTitles")]
    public async Task<IActionResult> GetEmployeeTitles()
    {
        var list = await _employeeService.GetAllTitles();
        var response = new
        {
            Items = list,
            Count = list.Count
        };
        return Json(response, serializerOptions);
    }
    
    [HttpPost("EmployeeTitles")]
    public async Task<IActionResult> PostEmployeeTitles(EmployeeTitle record)
    {
        if (!String.IsNullOrWhiteSpace(record.TitleName))
        {
            return Json(await _employeeService.AddEmployeeTitle(record), serializerOptions);
        }
        else
        {
            return StatusCode(400);
        }
    }
    
    [HttpPut("EmployeeTitles")]
    public async Task<IActionResult> PutEmployeeTitles(EmployeeTitle record)
    {
        return View();
    }
    
    [HttpDelete("EmployeeTitles")]
    public async Task<IActionResult> DeleteEmployeeTitles(EmployeeTitle record)
    {
        return View();
    }
    
    #endregion

    #region RoomType

    [HttpGet("RoomTypes")]
    public async Task<IActionResult> GetRoomTypes()
    {
        var list = await _roomService.GetRoomTypes();
        var response = new
        {
            Items = list,
            Count = list.Count
        };
        return Json(response, serializerOptions);
    }
    
    [HttpPost("RoomTypes")]
    public async Task<IActionResult> PostRoomTypes([FromBody] RoomType record)
    {
        if (!String.IsNullOrWhiteSpace(record.Name))
        {
            return Json(await _roomService.AddRoomType(record), serializerOptions);
        }
        else
        {
            return StatusCode(400);
        }
    }
    
    [HttpPut("RoomTypes")]
    public async Task<IActionResult> PutRoomTypes(RoomType record)
    {
        return View();
    }
    
    [HttpDelete("RoomTypes")]
    public async Task<IActionResult> DeleteRoomTypes(RoomType record)
    {
        return View();
    }

    #endregion

    #region RoomTarget

    [HttpGet("RoomTargets")]
    public async Task<IActionResult> GetRoomTargets()
    {
        var list = await _roomService.GetRoomTargets();
        var response = new
        {
            Items = list,
            Count = list.Count
        };
        return Json(response, serializerOptions);
    }
    
    [HttpPost("RoomTargets")]
    public async Task<IActionResult> PostRoomTargets([FromBody] RoomTarget record)
    {
        if (!String.IsNullOrWhiteSpace(record.TargetName))
        {
            return Json(await _roomService.AddRoomTarget(record), serializerOptions);
        }
        else
        {
            return StatusCode(400);
        }
    }
    
    [HttpPut("RoomTargets")]
    public async Task<IActionResult> PutRoomTargets(RoomTarget record)
    {
        return View();
    }
    
    [HttpDelete("RoomTargets")]
    public async Task<IActionResult> DeleteRoomTargets(RoomTarget record)
    {
        return View();
    }

    #endregion
}

ClassroomFund.FundUI/Controllers/ConstantsController.cs
using ClassroomFund.ScheduleUI.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ClassroomFund.ScheduleUI.Controllers;

[Authorize(Roles = RolesConstants.AdminRole)]
public class ConstantsController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

ClassroomFund.FundUI/Views/Constants/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "Управление константами";
    Layout = "_Layout";
}

<h2>Управление константами</h2>
<hr/>
<div class="row">
    <div class="col">
        <div class="accordion accordion-flush" id="constantsCollapsableView">
            <div class="accordion-item">
                <h2 class="accordion-header" id="employeeTitleHeader">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#employeeTitlesCollapseArea" aria-expanded="false" aria-controls="employeeTitlesCollapseArea">
                        Должности
                    </button>
                </h2>
                <div id="employeeTitlesCollapseArea" class="accordion-collapse collapse" aria-labelledby="employeeTitleHeader" data-bs-parent="#constantsCollapsableView">
                    <div class="accordion-body">
                        <ejs-grid id="employeeTitleGrid" toolbar="@(new List<string>() { "Add", "Delete", "Update", "Cancel" }) ">
                            <e-grid-editSettings allowDeleting="true" allowEditing="true" allowAdding="true"></e-grid-editSettings>
                            <e-data-manager url="@Url.Action("GetEmployeeTitles", "ConstantsApi")" adaptor="WebApiAdaptor" crossdomain="true"></e-data-manager>
                            <e-grid-columns>
                                <e-grid-column field="Id" headerText="ID" type="number" maxWidth="200" isPrimaryKey="true" isIdentity="true" allowEditing="false" editType="number"></e-grid-column>
                                <e-grid-column field="TitleName" headerText="Должность" type="string" maxWidth="200"></e-grid-column>
                            </e-grid-columns>
                        </ejs-grid>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="roomTypeHeader">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#roomTypeCollapseArea" aria-expanded="false" aria-controls="roomTypeCollapseArea">
                        Тип аудитории
                    </button>
                </h2>
                <div id="roomTypeCollapseArea" class="accordion-collapse collapse" aria-labelledby="roomTypeHeader" data-bs-parent="#constantsCollapsableView">
                    <div class="accordion-body">
                        <ejs-grid id="roomTypeGrid" toolbar="@(new List<string>() { "Add", "Delete", "Update", "Cancel" }) ">
                            <e-grid-editSettings allowDeleting="true" allowEditing="true" allowAdding="true"></e-grid-editSettings>
                            <e-data-manager url="@Url.Action("GetRoomTypes", "ConstantsApi")" adaptor="WebApiAdaptor" crossdomain="true"></e-data-manager>
                            <e-grid-columns>
                                <e-grid-column field="Id" headerText="ID" type="string" maxWidth="200" isPrimaryKey="true" isIdentity="true" allowEditing="false" defaultValue="Guid.Empty"></e-grid-column>
                                <e-grid-column field="Name" headerText="Должность" type="string" maxWidth="200"></e-grid-column>
                            </e-grid-columns>
                        </ejs-grid>
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="roomTargetHeader">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#roomTargetCollapseArea" aria-expanded="false" aria-controls="roomTargetCollapseArea">
                        Назначение аудитории
                    </button>
                </h2>
                <div id="roomTargetCollapseArea" class="accordion-collapse collapse" aria-labelledby="roomTargetHeader" data-bs-parent="#constantsCollapsableView">
                    <div class="accordion-body">
                        <ejs-grid id="roomTargetGrid" toolbar="@(new List<string>() { "Add", "Delete", "Update", "Cancel" }) ">
                            <e-grid-editSettings allowDeleting="true" allowEditing="true" allowAdding="true"></e-grid-editSettings>
                            <e-data-manager url="@Url.Action("GetRoomTargets", "ConstantsApi")" adaptor="WebApiAdaptor" crossdomain="true"></e-data-manager>
                            <e-grid-columns>
                                <e-grid-column field="Id" headerText="ID" type="number" maxWidth="200" isPrimaryKey="true" isIdentity="true" allowEditing="false" defaultValue="0"></e-grid-column>
                                <e-grid-column field="TargetName" headerText="Назначение" type="string" maxWidth="200"></e-grid-column>
                            </e-grid-columns>
                        </ejs-grid>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>